DEF title = 'Plans (v$sql_plan)';
DEF filename = 'Plans.html';
DEF nextpage = 'dba_hist_sql_plan.html';
DEF prevpage = 'activeSQLID.html';
@@sql/00_begin.sql

SPOOL html/Plans.txt REPLACE;
SPOOL OFF;
SET HEADING OFF;
SET MARKUP HTML OFF PREFORMAT OFF ENTMAP OFF;

SPOOL html/debug_plans.sql REPLACE;
PRO REM =======================================================================
PRO REM This file is automatically generated by sql/sqlid/Plans.sql
PRO REM
PRO REM Purpose: 
PRO REM   Driver script used to generate top query plans appended to Plans.html
PRO REM
PRO REM Notes:
PRO REM   - This file is NOT required to view generated HTML reports.
PRO REM   - It is intended solely for debugging Oracle report execution.
PRO REM   - Do NOT modify or run manually unless explicitly instructed by PTC Technical Support.
PRO REM
PRO REM =======================================================================
PRO

select '@sql/sqlid/display_cursor.sql &&enteredSQLID '||child_number 
from v$sql_plan
WHERE sql_id = '&&enteredSQLID'
AND id = 0
ORDER BY child_number ASC;

SPOOL html/Plans.html APPEND;
@@html/debug_plans.sql;

SPOOL OFF;
SET HEADING ON;

@@sql/00_end.sql
