/*
Replace oraperf with the username that will execute oracleperf.sql script
Replace WINDDBUSER with the Windchill schema
*/

-- Performance tables
GRANT SELECT ON WINDDBUSER.CACHESTATISTICS TO oraperf;
GRANT SELECT ON WINDDBUSER.JMXNOTIFICATIONS TO oraperf;
GRANT SELECT ON WINDDBUSER.LOG4JAVASCRIPTEVENTS TO oraperf;
GRANT SELECT ON WINDDBUSER.METHODCONTEXTS TO oraperf;
GRANT SELECT ON WINDDBUSER.METHODCONTEXTSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.METHODSERVERINFO TO oraperf;
GRANT SELECT ON WINDDBUSER.MISCLOGEVENTS TO oraperf;
GRANT SELECT ON WINDDBUSER.MSHEALTHSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.RAWMETHODCONTEXTSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.RAWSERVLETREQUESTSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.REMOTECACHESERVERCALLS TO oraperf;
GRANT SELECT ON WINDDBUSER.REQUESTHISTOGRAMS TO oraperf;
GRANT SELECT ON WINDDBUSER.RMIHISTOGRAMS TO oraperf;
GRANT SELECT ON WINDDBUSER.RMIPERFDATA TO oraperf;
GRANT SELECT ON WINDDBUSER.SAMPLEDMETHODCONTEXTS TO oraperf;
GRANT SELECT ON WINDDBUSER.SAMPLEDSERVLETREQUESTS TO oraperf;
GRANT SELECT ON WINDDBUSER.SERVERMANAGERINFO TO oraperf;
GRANT SELECT ON WINDDBUSER.SERVLETREQUESTS TO oraperf;
GRANT SELECT ON WINDDBUSER.SERVLETREQUESTSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.SERVLETSESSIONSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.SMHEALTHSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.TOPSQLSTATS TO oraperf;
GRANT SELECT ON WINDDBUSER.USERAGENTINFO TO oraperf;

-- Windchill installation history
GRANT SELECT ON WINDDBUSER.WTUPGINST_VERSIONEDASSEMBLY TO oraperf;
GRANT SELECT ON WINDDBUSER.WTUPGINST_INSTALLATION TO oraperf;

-- Queues
GRANT SELECT ON WINDDBUSER.QUEUEENTRY TO oraperf;
GRANT SELECT ON WINDDBUSER.PROCESSINGQUEUE TO oraperf;
