SELECT GROUP#, THREAD#, SEQUENCE#, BYTES/1048576 AS MB, 
  BLOCKSIZE, MEMBERS, ARCHIVED, STATUS, 
  FIRST_CHANGE#, TO_CHAR(FIRST_TIME, 'YYYY-MM-DD HH24:MI:SS') AS FIRST_TIME, 
  CASE STATUS WHEN 'CURRENT' THEN NULL ELSE NEXT_CHANGE# END AS NEXT_CHANGE#, 
  TO_CHAR(NEXT_TIME, 'YYYY-MM-DD HH24:MI:SS') AS NEXT_TIME
FROM V$LOG
ORDER BY GROUP#;
