SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK OFF;

SET TERMOUT ON VER OFF;
PRO If your Database is licensed to use the Oracle Tuning pack please enter T.
PRO If you have a license for Diagnostics pack but not for Tuning pack, enter D.
PRO If you have both Tuning and Diagnostics packs, enter T.
PRO If you are unsure about the license, enter N.
PRO Be aware value N eliminates queries to the AWR and ADDM.
PRO
PRO Oracle Pack License? (Tuning, Diagnostics or None) [ T | D | N ] (required)
--SET TERMOUT OFF VER OFF;
COL license_pack NEW_V license_pack FOR A12;
SELECT NVL(UPPER(SUBSTR(TRIM('&2.'), 1, 1)), '?') license_pack FROM DUAL;
WHENEVER SQLERROR EXIT SQL.SQLCODE;
BEGIN
  IF NOT '&&license_pack.' IN ('T', 'D', 'N') THEN
    RAISE_APPLICATION_ERROR(-20000, 'Invalid Oracle Pack License "&&license_pack.". Valid values are T, D and N.');
  END IF;
END;
/
WHENEVER SQLERROR CONTINUE;

-- Check if user has access to DBMS_WORKLOAD_REPOSITORY. This is necessary to generate AWR reports
SET TERMOUT OFF VER OFF;
COL workload_access_granted NEW_VALUE workload_access_granted FOR A48;
SELECT 'None' workload_access_granted FROM DUAL;
WITH exec_workload AS (
SELECT grantee
    FROM USER_TAB_PRIVS
WHERE table_name = 'DBMS_WORKLOAD_REPOSITORY'
AND privilege = 'EXECUTE'
)
SELECT exec_workload.grantee, 'USER' AS workload_access_granted
FROM exec_workload
WHERE grantee = USER
UNION ALL
SELECT exec_workload.grantee, 'ROLE' AS workload_access_granted
FROM exec_workload, USER_ROLE_PRIVS urp
WHERE urp.granted_role = exec_workload.grantee
AND urp.username = USER;

SET TERMOUT OFF VER OFF;
COL is_enterprise NEW_V is_enterprise FOR A1;
SELECT (select 'E' from v$version where banner like '%Enterprise Edition%') is_enterprise from dual;

--PRO license_pack entered: &&license_pack
PRO Generating 99_Column5_AWR.sql

SET TERMOUT OFF
SPOOL sql/99_Column5_AWR.sql REPLACE

BEGIN
dbms_output.put_line('--generated by 00_license.sql');
dbms_output.put_line('--License Pack Entered: &&license_pack');
dbms_output.put_line('--Workload access granted by: &&workload_access_granted');

IF '&&license_pack' IN ('T','D') AND '&&is_enterprise' = 'E' THEN
    IF '&&workload_access_granted' = 'None' THEN
      dbms_output.put_line('@@sql/AwrRetention.sql');
      dbms_output.put_line('SET TERMOUT ON');
      dbms_output.put_line('PRO AWR SKIPPED. User does not have access to DBMS_WORKLOAD_REPOSITORY');
      dbms_output.put_line('SET TERMOUT OFF');
      dbms_output.put_line('SPOOL html/00_oracleperf.html APPEND;');
      dbms_output.put_line('PRO <br>');
      dbms_output.put_line('PRO <li>AWR SKIPPED. User does not have access to DBMS_WORKLOAD_REPOSITORY</li>');
      dbms_output.put_line('PRO <br>');
      dbms_output.put_line('SPOOL OFF;');
    ELSE
      dbms_output.put_line('@@sql/AwrRetention.sql');
      dbms_output.put_line('@@sql/AwrSqlReports.sql');
      dbms_output.put_line('@@sql/AwrReports.sql');
    END IF;
ELSE
    dbms_output.put_line('SET TERMOUT ON');
    dbms_output.put_line('PRO AWR SKIPPED');
    dbms_output.put_line('SET TERMOUT OFF');
END IF;
END;
/
SPOOL OFF;
