SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK OFF;

SET TERMOUT ON VER OFF;
PRO If your Database is licensed to use the Oracle Tuning pack please enter T.
PRO If you have a license for Diagnostics pack but not for Tuning pack, enter D.
PRO If you have both Tuning and Diagnostics packs, enter T.
PRO If you are unsure about the license, enter N.
PRO Be aware value N eliminates queries to the AWR and ADDM.
PRO
PRO Oracle Pack License? (Tuning, Diagnostics or None) [ T | D | N ] (required)
--SET TERMOUT OFF VER OFF;
COL license_pack NEW_V license_pack FOR A12;
SELECT NVL(UPPER(SUBSTR(TRIM('&2.'), 1, 1)), '?') license_pack FROM DUAL;
WHENEVER SQLERROR EXIT SQL.SQLCODE;
BEGIN
  IF NOT '&&license_pack.' IN ('T', 'D', 'N') THEN
    RAISE_APPLICATION_ERROR(-20000, 'Invalid Oracle Pack License "&&license_pack.". Valid values are T, D and N.');
  END IF;
END;
/
WHENEVER SQLERROR CONTINUE;

SET TERMOUT OFF VER OFF;
COL is_enterprise NEW_V is_enterprise FOR A1;
SELECT (select 'E' from v$version where banner like '%Enterprise Edition%') is_enterprise from dual;

--PRO license_pack entered: &&license_pack
PRO Generating 99_Column5_AWR.sql

SET TERMOUT OFF
SPOOL sql/99_Column5_AWR.sql REPLACE

BEGIN
dbms_output.put_line('--generated by 00_license.sql');
IF '&&license_pack' IN ('T','D') AND '&&is_enterprise' = 'E' THEN
    dbms_output.put_line('@@sql/AwrRetention.sql');
    dbms_output.put_line('@@sql/AwrSqlReports.sql');
    dbms_output.put_line('@@sql/AwrReports.sql');
ELSE
    dbms_output.put_line('SET TERMOUT ON');
    dbms_output.put_line('PRO AWR SKIPPED');
    dbms_output.put_line('SET TERMOUT OFF');
END IF;
END;
/
SPOOL OFF;

SET TERMOUT OFF VER OFF;
