DEF filename = '99_AwrSqlReports-Driver.sql';

SET TERMOUT ON;
PRO Generating &&filename
SET TERMOUT OFF;

set serveroutput on size unlimited;
set linesize 1000;
SET HEADING OFF;
SET MARKUP HTML ENTMAP OFF;

SPOOL sql/99_AwrSqlReports-Driver.sql REPLACE

DECLARE /*gather_info_script*/

    lv_dbid v$database.dbid%TYPE;
    lv_instance_number v$instance.instance_number%TYPE;
    v_snap_id_start number;
    v_snap_id_end number;

BEGIN
dbms_output.put_line('--generated by AwrSqlReports.sql');
    SELECT dbid INTO lv_dbid FROM v$database;
    SELECT instance_number INTO lv_instance_number FROM v$instance;
    
--Average Elapsed Time:
    FOR cur_snap IN (select sql_id, min_snap, max_snap, avg_time FROM (
        WITH 
          sqlavg AS (SELECT ss.sql_id, 
            MAX(ss.snap_id) max_snap_id,
            SUM(ss.executions_delta) sum_executions,
            SUM(ss.elapsed_time_delta) sum_elapsed_time,
            ROUND(SUM(ss.elapsed_time_delta)/1000000/SUM(nvl(nullif(ss.executions_delta,0),1)),2) avg_time
          FROM dba_hist_sqlstat ss, dba_hist_snapshot snap, dba_hist_sqltext sqltext
          WHERE ss.snap_id not in (select max(snap_id) from dba_hist_sqlstat)
            and ss.snap_id = snap.snap_id
            and ss.sql_id = sqltext.sql_id
            and snap.begin_interval_time >= SYSDATE - 7 --Only consider the last 7 days
            and ss.parsing_schema_name not in 
            ('ANONYMOUS','APPQOSSYS','AUDSYS','BI','CTXSYS','DBSNMP','DIP','DMSYS','EXFSYS',
            'GSMADMIN_INTERNAL','HR','IX','MDDATA','MDSYS','MGMT_VIEW','ODM','ODM_MTR','OE',
            'OLAPSYS','ORDPLUGINS','ORDSYS','OUTLN','PM','QS','QS_CBADM','QS_CS','QS_ES',
            'QS_OS','QS_WS','SCOTT','SH','SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM',
            'TSMSYS','WKSYS','WMSYS','XDB')
            AND ss.module <> 'DBMS_SCHEDULER'
            and sqltext.sql_text not like '/* SQL Analyze(%'
            and sqltext.sql_text not like '%/* DS_SVC%'
            and sqltext.sql_text not like 'BEGIN DBMS_STATS%'
          GROUP BY ss.sql_id
          ORDER BY avg_time DESC),
          
        snap_range AS (
        SELECT ss.sql_id, min(snap.snap_id)-1 min_snap, max(snap.snap_id) max_snap
          FROM dba_hist_sqlstat ss, dba_hist_snapshot snap, dba_hist_sqltext sqltext
        WHERE ss.snap_id not in (select max(snap_id) from dba_hist_sqlstat)
          and ss.snap_id = snap.snap_id
          and ss.sql_id = sqltext.sql_id
          and snap.begin_interval_time >= SYSDATE - 7 --Only consider the last 7 days
          and ss.parsing_schema_name not in 
            ('ANONYMOUS','APPQOSSYS','AUDSYS','BI','CTXSYS','DBSNMP','DIP','DMSYS','EXFSYS',
            'GSMADMIN_INTERNAL','HR','IX','MDDATA','MDSYS','MGMT_VIEW','ODM','ODM_MTR','OE',
            'OLAPSYS','ORDPLUGINS','ORDSYS','OUTLN','PM','QS','QS_CBADM','QS_CS','QS_ES',
            'QS_OS','QS_WS','SCOTT','SH','SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM',
            'TSMSYS','WKSYS','WMSYS','XDB')
            and sqltext.sql_text not like '/* SQL Analyze(%'
            and sqltext.sql_text not like '%/* DS_SVC%'
            and sqltext.sql_text not like 'BEGIN DBMS_STATS%'
        GROUP BY ss.sql_id, snap.startup_time
        ORDER BY ss.sql_id
        ),

        max_snap_range AS(
        SELECT sql_id, MAX(min_snap) min_snap, MAX(max_snap) max_snap
        FROM snap_range
        GROUP BY sql_id
        )

        SELECT * FROM (
        SELECT sqlavg.sql_id, max_snap_range.min_snap, max_snap_range.max_snap, sqlavg.avg_time
        FROM sqlavg, max_snap_range
        WHERE sqlavg.sql_id = max_snap_range.sql_id
          AND sqlavg.max_snap_id = max_snap_range.max_snap
        ORDER BY sqlavg.avg_time desc
        ) WHERE ROWNUM <= 10
    ))
    LOOP
        dbms_output.put_line('SET TERMOUT ON;');
        dbms_output.put_line('PRO Generating AWR-SQLID-'||cur_snap.sql_id||'.html');
        dbms_output.put_line('SET TERMOUT OFF;');
        dbms_output.put_line('SPOOL html/AWR-SQLID-'||cur_snap.sql_id||'.html REPLACE');
        dbms_output.put_line('SELECT output FROM TABLE(DBMS_WORKLOAD_REPOSITORY.awr_sql_report_html('||lv_dbid||','||lv_instance_number||','||cur_snap.min_snap||','||cur_snap.max_snap||','''||cur_snap.sql_id||'''));');
        dbms_output.put_line('SPOOL html/00_oracleperf.html APPEND');
        dbms_output.put_line('PRO <li><a href="AWR-SQLID-'||cur_snap.sql_id||'.html">AWR-SQLID-'||cur_snap.sql_id||'</a> avg_sec: '||cur_snap.avg_time||'</li>');
        dbms_output.put_line('SPOOL OFF');
    END LOOP;
        dbms_output.put_line('SPOOL html/00_oracleperf.html APPEND');
        dbms_output.put_line('PRO <br>');
        dbms_output.put_line('SPOOL OFF');
--Average Buffer Gets
    FOR cur_snap IN (select sql_id, min_snap, max_snap, avg_gets FROM (
        WITH 
          sqlavg AS (SELECT ss.sql_id, 
            MAX(ss.snap_id) max_snap_id,
            SUM(ss.executions_delta) sum_executions,
            SUM(ss.buffer_gets_delta) sum_buffer_gets,
            ROUND(SUM(ss.buffer_gets_delta)/SUM(nvl(nullif(ss.executions_delta,0),1))) avg_gets
          FROM dba_hist_sqlstat ss, dba_hist_snapshot snap, dba_hist_sqltext sqltext
          WHERE ss.snap_id not in (select max(snap_id) from dba_hist_sqlstat)
            and ss.snap_id = snap.snap_id
            and ss.sql_id = sqltext.sql_id
            and snap.begin_interval_time >= SYSDATE - 7 --Only consider the last 7 days
            and ss.parsing_schema_name not in 
            ('ANONYMOUS','APPQOSSYS','AUDSYS','BI','CTXSYS','DBSNMP','DIP','DMSYS','EXFSYS',
            'GSMADMIN_INTERNAL','HR','IX','MDDATA','MDSYS','MGMT_VIEW','ODM','ODM_MTR','OE',
            'OLAPSYS','ORDPLUGINS','ORDSYS','OUTLN','PM','QS','QS_CBADM','QS_CS','QS_ES',
            'QS_OS','QS_WS','SCOTT','SH','SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM',
            'TSMSYS','WKSYS','WMSYS','XDB')
            and sqltext.sql_text not like '/* SQL Analyze(%'
            and sqltext.sql_text not like '%/* DS_SVC%'
            and sqltext.sql_text not like 'BEGIN DBMS_STATS%'
          GROUP BY ss.sql_id
          ORDER BY avg_gets DESC),
          
        snap_range AS (
        SELECT ss.sql_id, min(snap.snap_id)-1 min_snap, max(snap.snap_id) max_snap
          FROM dba_hist_sqlstat ss, dba_hist_snapshot snap, dba_hist_sqltext sqltext
        WHERE ss.snap_id not in (select max(snap_id) from dba_hist_sqlstat)
          and ss.snap_id = snap.snap_id
          and ss.sql_id = sqltext.sql_id
          and snap.begin_interval_time >= SYSDATE - 7 --Only consider the last 7 days
          and ss.parsing_schema_name not in 
            ('ANONYMOUS','APPQOSSYS','AUDSYS','BI','CTXSYS','DBSNMP','DIP','DMSYS','EXFSYS',
            'GSMADMIN_INTERNAL','HR','IX','MDDATA','MDSYS','MGMT_VIEW','ODM','ODM_MTR','OE',
            'OLAPSYS','ORDPLUGINS','ORDSYS','OUTLN','PM','QS','QS_CBADM','QS_CS','QS_ES',
            'QS_OS','QS_WS','SCOTT','SH','SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM',
            'TSMSYS','WKSYS','WMSYS','XDB')
            and sqltext.sql_text not like '/* SQL Analyze(%'
            and sqltext.sql_text not like '%/* DS_SVC%'
            and sqltext.sql_text not like 'BEGIN DBMS_STATS%'
        GROUP BY ss.sql_id, snap.startup_time
        ORDER BY ss.sql_id
        ),

        max_snap_range AS(
        SELECT sql_id, MAX(min_snap) min_snap, MAX(max_snap) max_snap
        FROM snap_range
        GROUP BY sql_id
        )

        SELECT * FROM (
        SELECT sqlavg.sql_id, max_snap_range.min_snap, max_snap_range.max_snap, sqlavg.avg_gets
        FROM sqlavg, max_snap_range
        WHERE sqlavg.sql_id = max_snap_range.sql_id
          AND sqlavg.max_snap_id = max_snap_range.max_snap
        ORDER BY sqlavg.avg_gets desc
        ) WHERE ROWNUM <= 10
    ))
    LOOP
        dbms_output.put_line('SET TERMOUT ON;');
        dbms_output.put_line('PRO Generating AWR-SQLID-'||cur_snap.sql_id||'.html');
        dbms_output.put_line('SET TERMOUT OFF;');
        dbms_output.put_line('SPOOL html/AWR-SQLID-'||cur_snap.sql_id||'.html REPLACE');
        dbms_output.put_line('SELECT output FROM TABLE(DBMS_WORKLOAD_REPOSITORY.awr_sql_report_html('||lv_dbid||','||lv_instance_number||','||cur_snap.min_snap||','||cur_snap.max_snap||','''||cur_snap.sql_id||'''));');
        dbms_output.put_line('SPOOL html/00_oracleperf.html APPEND');
        dbms_output.put_line('PRO <li><a href="AWR-SQLID-'||cur_snap.sql_id||'.html">AWR-SQLID-'||cur_snap.sql_id||'</a> avg_gets: '||cur_snap.avg_gets||'</li>');
        dbms_output.put_line('SPOOL OFF');
    END LOOP;
END;
/
SPOOL OFF
@@sql/99_AwrSqlReports-Driver.sql

SET HEADING ON;