DEF title = 'PDB Info';
DEF filename = 'PDBInfo.html';
@@00_begin.sql

--Confirms whether we're connected to a PDB or the root container (CDB)
SELECT CASE
         WHEN sys_context('USERENV','CON_ID') > 1 THEN 'IS PDB'
         WHEN sys_context('USERENV','CON_ID') = 1 THEN 'IS CDB'
         ELSE 'IS NOT PDB/CDB' 
       END "IsMultiTenant"
FROM DUAL;

--Tracks historical resource plan metrics per PDB
SELECT *
FROM V$RSRC_PDB_HISTORY
ORDER BY CON_ID, SEQUENCE# DESC;

--Trending resource usage across PDB(s)
SELECT CON_ID,
       TO_CHAR(begin_time,'DD-MON-YYYY HH24:MI:SS') AS BEGIN_TIME,
       TO_CHAR(end_time,'DD-MON-YYYY HH24:MI:SS') AS END_TIME,
       INTSIZE_CSEC, SEQUENCE#,
       ROUND(SGA_BYTES/POWER(1024,3),3) AS SGA_GB,
       ROUND(BUFFER_CACHE_BYTES/POWER(1024,3),3) AS BUFFER_CACHE_GB,
       ROUND(SHARED_POOL_BYTES/POWER(1024,3),3) AS SHARED_POOL_GB,
       ROUND(PGA_BYTES/POWER(1024,3),3) AS PGA_BYTES_GB,
       CPU_CONSUMED_TIME, CPU_WAIT_TIME, NUM_CPUS, RUNNING_SESSIONS_LIMIT,
       ROUND(AVG_RUNNING_SESSIONS,2) AS AVG_RUNNING_SESSIONS,
       ROUND(AVG_WAITING_SESSIONS,2) AS AVG_WAITING_SESSIONS,
       CPU_UTILIZATION_LIMIT, ROUND(AVG_CPU_UTILIZATION,2) AS AVG_CPU_UTILIZATION,
       ROUND(IOPS,2) AS IOPS, ROUND(IOMBPS,2) AS IOMBPS,
       ROUND(IOPS_THROTTLE_EXEMPT,2) AS IOPS_THROTTLE_EXEMPT,
       ROUND(IOMBPS_THROTTLE_EXEMPT,2) AS IOMBPS_THROTTLE_EXEMPT,
       ROUND(AVG_IO_THROTTLE,2) AS AVG_IO_THROTTLE,
       ROUND(AVG_ACTIVE_PARALLEL_STMTS,2) AS AVG_ACTIVE_PARALLEL_STMTS,
       ROUND(AVG_QUEUED_PARALLEL_STMTS,2) AS AVG_QUEUED_PARALLEL_STMTS,
       ROUND(AVG_ACTIVE_PARALLEL_SERVERS,2) AS AVG_ACTIVE_PARALLEL_SERVERS,
       ROUND(AVG_QUEUED_PARALLEL_SERVERS,2) AS AVG_QUEUED_PARALLEL_SERVERS,
       PARALLEL_SERVERS_LIMIT, PLAN_NAME
FROM V$RSRCPDBMETRIC_HISTORY
ORDER BY CON_ID, BEGIN_TIME DESC;


@@00_end.sql